### PR TITLE
Replaced node's 'url' module with 'url-parse' to support 'dat://' in node.js

### PR DESCRIPTION
**Pull request by AnsonT**
Fixes: https://github.com/beakerbrowser/ingestdb/issues/2

### CODE REVIEW

**Comment by pfrazee** [comment]
Thanks for the PR! Can you give me an example URL that was failing the parse? I want to have a test that reproduces the error.

**Comment by AnsonT** [comment]
```javascript
import DatArchive from 'node-dat-archive'
import Injest from 'injestdb'
import tempy from 'tempy'

async function test() {
  const a = await DatArchive.create({localPath: tempy.directory()})
  const dir = tempy.directory()
  const db = new Injest(dir, {DatArchive})
  db.schema({
    version: 1,
    posts: {
      primaryKey: 'id',
      index: ['id'],
      validator: record => (record)
    }
  })
  try {
    await db.open()
    await db.addArchive(a)
    await db.posts.add(a, { id: '1', text: '123' })
    await db.posts.add(a, { id: '2', text: 'abc' })
    const post = await db.posts.get(a, '1')
    console.log(post)
  }
  catch (e)  {
    console.log(e)
  }
}

test()
```

**Comment by pfrazee** [comment]
That runs fine to me, and of course I just realized: what version of node are you on? I think the URL API I'm using is a new addition.

**Comment by pfrazee** [comment]
Yeah the new API is v7+. I'll go ahead and merge, only ~20kb more.

**Comment by pfrazee** [comment]
Published `2.4.6`

**Comment by AnsonT** [comment]
Sorry, you are right, it’s the node version. I upgraded to 8.6.0 and URL function accepts dat://.

 

Thanks,

Anson

**Pull request merged**
